on:
  issues:
    types: [labeled]

jobs:
  move_on_label:
    runs-on: ubuntu-latest
    name: Move to project on label
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          script: |
            const path = require('path')
            const scriptPath = path.resolve('.github/workflows/js/projectBasedOnLabel.js')
            console.log(require(scriptPath)({context, github}))
