on:
  issues:
    types: [labeled]

jobs:
  move_on_label:
    runs-on: ubuntu-latest
    name: Move to project on label
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          script: |
            const workflowIssue = ["c: SQL Editor"].includes(context.payload.label.name);
            const priorityExists = ["P0", "P1", "P2", "P3"].filter(label => context.payload.issue.labels.includes(label));
            if (workflowIssue && priorityExists) {
              github.projects.createCard({
                column_id: 9962014,
                content_id: context.payload.issue.id,
                content_type: "Issue",
              })
            } else {
              console.log("Not ready for Eng", context.payload)
            }
