on:
  issues:
    types: [labeled]

jobs:
  move_on_label:
    runs-on: ubuntu-latest
    name: Move to project on label
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
              const path = require('path')
              const scriptPath = path.resolve('./index.js')
              console.log(require(scriptPath)({context}))

# on:
#   issues:
#     types: [opened]

# jobs:
#   comment:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/github-script@v2
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#           script: |
#             github.issues.createComment({
#               issue_number: context.issue.number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               body: '👋 Thanks for reporting!'
#             })
