on:
  issues:
    types: [labeled]

jobs:
  move_on_label:
    runs-on: ubuntu-latest
    name: Move to project on label
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          script: |
            context.payload.label === "help wanted"
              ? payload.github.projects.createCard({
                  column_id: 9962014,
                  content_id: context.payload.issue.id,
                  content_type: "Issue",
                });
              : console.log("wrong label")
