on:
  issues:
    types: [labeled]

jobs:
  move_on_label:
    runs-on: ubuntu-latest
    name: Move to project on label
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          script: |
            github.projects.createCard({
              column_id: 9962014,
              content_id: contex.issue.id,
              content_type: "Issue",
            });

# on:
#   issues:
#     types: [opened]

# jobs:
#   comment:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/github-script@v2
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#           script: |
#             github.issues.createComment({
#               issue_number: context.issue.number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               body: '👋 Thanks for reporting!'
#             })
