on:
  issues:
    types: [labeled]

jobs:
  reactive_move_on_label:
    runs-on: ubuntu-latest
    name: Move to project on label
    steps:
      - name: Move to project on label
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          with:
          script: |
            const path = require('path')
            const scriptPath = path.resolve('./index.js')
            console.log(require(scriptPath)({context}))
