on:
  issues:
    types: [labeled]

jobs:
  move_on_label:
    runs-on: ubuntu-latest
    name: Move to project on label
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          script: |
            if(context.payload.label.name === "help wanted") {
              github.projects.createCard({
                column_id: 9962014,
                content_id: context.payload.issue.id,
                content_type: "Issue",
              })
            } else {
              console.log("wrong label", context.payload)
            }
  rcoket:
    runs-on: ubuntu-latest
    name: Rocket reply
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          script: |
            github.reactions.createForIssue({
              owner,
              repo,
              issue_number,
              content,
            });
