on:
  issues:
    types: [labeled]

jobs:
  move_on_label:
    runs-on: ubuntu-latest
    name: Move to project on label
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          script: |
            const { issue, label } = context.payload;
            if(label.name === "help wanted") {
              payload.github.projects.createCard({
                column_id: 9962014,
                content_id: issue.id,
                content_type: "Issue",
              })
            } else {
              console.log("wrong label", context.payload)
            }
